apiVersion: apps/v1
kind: Deployment
metadata:
    name: rmm-agent
    namespace: stage
spec:
    replicas: 1
    selector:
      matchLabels:
        app: rmm-agent
    template:
      metadata:
        labels:
           app: rmm-agent
      spec:
        containers:
        - name: rmm-agent
          image: REPLACE_ME
          ports:                                                                                                                   - containerPort: 8080
