apiVersion: v1
kind: Service
metadata:
  name: rmm-agent-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: rmm-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
