apiVersion: v1
kind: Service
metadata:
    name: rmm-agent
    namespace: stage
spec:
    type: NodePort
    selector:
       app: rmm-agent
    ports:
       - protocol: TCP
         port: 8080
         targetPort: 8080

